### ISSUE TITLE
Looking for examples on dumping all firewall rules

### ISSUE THREAD

**Issue by Martin4Kansas** [CheckPointSW/cpAnsible#15]
Hi folks,

I'm still learning Ansible, so I'm not yet an expert on iterating through dictionaries, json, etc.  I have been able to make the command show-access-layers.  I want to use that result to loop through the access-layers and display the rules pertaining to each one.  Does anyone have an example I may look at that accomplishes this?

Thanks!

**Comment by nbo32** [comment]
Hi

Not sure about the exact question :/

You are looking for Check Point API "show-access-rulebase" ?

I don't know if you are aware but Check Point API list is available here :
https://sc1.checkpoint.com/documents/latest/APIs/index.html#gui-cli/show-access-rulebase~v1.2%20

**Comment by Martin4Kansas** [comment]
I know of the command show-access-rulebase.  I would like to use the results of the command show-access-layers to dynamically make multiple show-access-rulebase commands.  I'm unsure of how to parse the result and use it for other commands, though.

**Comment by chkp-rdecker** [comment]
The result data is returned in JSON format, very easy to parse. You just need to know the structure.
You can run a raw mgmt_cli commands on your management to see the output.
In which environment do you intend to use to process the data? Python?

**Comment by Martin4Kansas** [comment]
Preferably, I'd like to do it in Ansible so that I would only have to run one playbook that outputs all of the firewall rules to a text file.

**Comment by chkp-rdecker** [comment]
Well, in this case you need to expertise in Ansible YML scripting.
Anyway, you have to be familiar with the structure of the API commands output in order to manipulate it,
so you also need to use raw mgmt_cli commands and examine the output.

**Comment by Martin4Kansas** [comment]
I'm pretty familiar with the API output and I'm getting better at Ansible YML scripting.  The issue is just parsing the response which it appears is read by Ansible as a nested dictionary.  I mainly am looking for an example as hopefully someone, maybe @JonTheNiceGuy has done something like this.

**Comment by JonTheNiceGuy** [comment]
I'll be honest, I've not taken a look recently, but you can iterate over data in Ansible pretty easily, like this (this is without looking at what a Check Point API returns for a rulebase):

````yaml
- hosts: localhost
  tasks:
# Login to your Check Point API first!
  - name: Get rulebase
    check_point_mgmt:
      command: show-access-rulebase
      session-data: "{{ login_response }}"
    register: example
  - name: loop 1
    debug: 
      msg: |
{% for entry in example.rulebase %}
{{ entry.source }} -> {{ entry.destination }}
{% endfor %}
  - name: loop 2
    debug:
      msg: "{{ item.value.source }} -> {{ item.value.destination }}"
    loop: "{{ example.rulebase }}"
    loop_control:
      label: "{{ item.key }}"
````

Sadly, this hasn't been done with any real data as I've been distracted away from this for the past few months, but I think it's due to come back up again soonish.

I did have a poke at this after finding [the docs for the show-access-rulebase command](https://sc1.checkpoint.com/documents/latest/APIs/index.html#gui-cli/show-access-rulebase~v1.2%20) where you can see an example of the JSON output. I then fed it into http://jsonviewer.stack.hu/ to parse the output in a slightly more readable fashion. It looks like you might need to find values from the objects dictionary using stanzas like this: 
````yaml
{% for object in example['objects-dictionary'] %}{% if object.uid == search_value %}{{ object.name %}{% endif %}{% endfor %}
```` 
or perhaps create a new array like this:

````yaml
  tasks:
  - set_fact: 
      objects_dictionary: "[{% for item in example['objects-dictionary'] %}'{{ item.uid }}': {{ item }}{% if not loop.last %}, {% endif %}{% endfor %}]"
  - debug:
      var: objects_dictionary['decafbad-dead-beef-1234-12345678901']
````

Hope this helps. Like I said, I should be taking a look later!
