### ISSUE TITLE
How to use show-changes

### ISSUE THREAD

**Issue by 86label** [CheckPointSW/cpAnsible#25]
Hi,
First off thanks for the module. 
I've made a playbook that first checks for existing objects, then creates missing objects I need if they don't exist. It works.
Now instead of registering all changes along the way and compiling a list, I would like to use "show-changes" https://sc1.checkpoint.com/documents/latest/APIs/index.html#web/show-changes~v1.1%20 .
I just can't seem to get it to work.
I've tried the following:
```
  - name: show changes
    check_point_mgmt:
      command: show-changes
      parameters:
        from-session: "{{ showsession.response.uid }}"
        to-session: "{{ showsession2.response.uid }}"
        limit: 500
      session-data: '{{ login_response }}'
```
If I run above with only from session (=same session), I get 0 changes back. A diff on the same session would give 0 so that's expected - but I do get a valid response from the API.
My thought was then to 
login -> show-session (get uid for this session) -> logout
login again -> show-session (get uid of this second session) -> do all changes (publish shows "numberOfPublishedChanges": 200)
-> show-changes 
However, done with from-session and to-session I get:
```
"code": "generic_err_object_not_found"
"message": "Work Session with UID <uid here>"
```
The session it cannot find is the second session. I've tried making a 3rd session that gets changes from the previous two, same error the session with the changes can't be found.
Any pointers? 
Thanks in advance
