### ISSUE TITLE
add-host command is returning invalid JSON response

### ISSUE THREAD

**Issue by Mazimer** [CheckPointSW/cpAnsible#5]
i'm using a playbook akin to this (redacted variables where needed):
 ```
- name: "login task"
  hosts: localhost
  connection: local
  tasks:
  - name: login to mgmt
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: <mgmt_ip>
      fingerprint: <fingerpring obtained from running playbook with -C option>
    register: login_response
  - name: adding a demo host
    check_point_mgmt:
      command: add-host
      parameters:
        name: <hostname>
        ip-address: <host_ip>
      session-data: "{{ login_response }}"
  - name: logout
    check_point_mgmt:
      command: logout
      session-data: '{{login_response}}'
```

and i'm getting a response like this:

```
fatal: [172.31.250.11]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command": "add-host",
            "fingerprint": null,
            "parameters": "{'name': '<hostname>', 'ip-address': '<host_ip>'}",
            "session-data": "{'failed': False, 'changed': False, 'response': {'url': '<mgmt_ip>:443', 'domain': None, 'sid': None, 'fingerprint': <fingerpring obtained from running playbook with -C option>}}"
        }
    },
    "msg": "Command 'add-host {u'name': u'<hostname>', u'ip-address': u'<host_ip>'}' failed with error message: APIResponse received a response which is not a valid JSON.. All changes are discarded and the session is invalidated."
}

```

note that the login task is successful. am i missing something or is this a bug?

EDIT: found this issue under closed ones...

SOLUTION:
API was not activated on the management server, only on the firewall nodes that i was using to access the management server.
