### ISSUE TITLE
Documentation about getting API fingerprint

### ISSUE THREAD

**Issue by Martin4Kansas** [CheckPointSW/cpAnsible#9]
I think your documentation for getting the API fingerprint is either incorrect or misleading as I cannot for the life of me figure out how to obtain it.  I have typed api fingerprint, run api fingerprint, run "api fingerprint" and several other combinations into the SmartConsole command line, but it never recognizes the command.  How do you obtain the API fingerprint?  And can you please make it more clear in your documentation?  Thanks!

**Comment by JonTheNiceGuy** [comment]
I wrote an ansible playbook to turn an unconfigured appliance into a self-managed appliance, including enabling the API service. Here's what I wrote:

````yaml
---
- name: Waiting for the host to boot
  wait_for:
    port: 22
    host: "{{ ansible_host|default(ansible_ssh_host|default(inventory_hostname)) }}"
    timeout: 65535
  connection: local

- name: Configure device for Ansible Management
  raw: "set user {{ ansible_ssh_user|default(ansible_user|default('admin')) }} shell /bin/bash"

- name: "Just give us a few more minutes ;) (Waiting for the socket to close)"
  wait_for:
    port: 22
    host: "{{ ansible_host|default(ansible_ssh_host|default(inventory_hostname)) }}"
    delay: 80
  connection: local

- name: Prepare device for self-management
  raw: "echo \"sleep 10 ; . /etc/profile.d/CP.sh ; config_system -s 'ftw_sic_key={{ default_sic_password|default('vpn123') }}&install_security_gw={{ device_is_gateway|default('true') }}&install_ppak={{ device_is_gateway|default('true') }}&install_security_managment={{ device_is_manager|default('true') }}&install_mgmt_primary={{ device_is_manager|default('true') }}&install_mgmt_secondary={{ device_is_ha_manager|default('false') }}&install_mds_primary=false&install_mds_secondary=false&mgmt_gui_clients_radio=any&download_info=false&upload_info=false&mgmt_admin_name=admin&mgmt_admin_passwd={{ default_password|default('vpn123') }}&mgmt_gui_clients_radio=any&timezone={{ device_timezone|default('Europe/London') }}&reboot_if_required=true' | logger -t config_system\" > /home/{{ ansible_ssh_user|default(ansible_user|default('admin')) }}/runcmd.sh"

- name: Configure device for self-management
  raw: "(nohup /bin/bash /home/{{ ansible_ssh_user|default(ansible_user|default('admin')) }}/runcmd.sh &) && sleep 5"
  ignore_errors: true

- name: Wait for CPMI to become available
  wait_for:
    port: 18190
    host: "{{ ansible_host|default(ansible_ssh_host|default(inventory_hostname)) }}"
    delay: 180
    timeout: 65535
  connection: local

- name: Start the API service
  raw: . /etc/profile.d/CP.sh ; api restart

- name: Login to the API
  raw: . /etc/profile.d/CP.sh ; mgmt_cli login -r true domain "System Data" > "/home/{{ ansible_ssh_user|default(ansible_user|default('admin')) }}/session"

- name: Reconfigure the API to permit GUI client addresses
  raw: . /etc/profile.d/CP.sh ; mgmt_cli -s "/home/{{ ansible_ssh_user|default(ansible_user|default('admin')) }}/session" set api-settings accepted-api-calls-from "all ip addresses that can be used for gui clients"

- name: Publish updates
  raw: . /etc/profile.d/CP.sh ; mgmt_cli -s "/home/{{ ansible_ssh_user|default(ansible_user|default('admin')) }}/session" publish

- name: Restart the API service
  raw: . /etc/profile.d/CP.sh ; api restart

- name: Configure device for Ansible Management
  raw: "clish -c 'set user {{ ansible_ssh_user|default(ansible_user|default('admin')) }} shell /etc/cli.sh' -s"

- name: "Just give us a few more minutes ;) (Waiting for the socket to close)"
  wait_for:
    port: 22
    host: "{{ ansible_host|default(ansible_ssh_host|default(inventory_hostname)) }}"
    delay: 80
  connection: local
````

Then I had a separate playbook (because you only need to run that once) to actually make the changes:

````yaml
---
- name: Ask for the API 
  raw: api fingerprint
  register: api_fingerprint_raw

- name: Parse API response to derive the fingerprint
  set_fact:
    api_fingerprint: "{{ item.split(' ')[1] }}"
  with_items: "{{ api_fingerprint_raw.stdout_lines }}"
  when: ('SHA1:' in item)

- name: "login task"
  delegate_to: localhost
  check_point_mgmt:
    command: login
    parameters:
      username: "{{ ansible_user|default('admin') }}"
      password: "{{ ansible_ssh_pass|default('vpn123') }}"
      management: "{{ inventory_hostname }}"
    fingerprint: "{{ api_fingerprint|default('Unknown') }}"
  register: login_response
  when: api_fingerprint is defined

- name: Create host objects
  delegate_to: localhost
  check_point_mgmt:
    command: add-host
    parameters:
      name: "{{ item.key }}"
      ip-address: "{{ item.value }}"
    session-data: "{{ login_response }}"
  with_dict: "{{ policy_hosts }}"

- name: Publish
  delegate_to: localhost
  check_point_mgmt:
    command: publish
    session-data: "{{ login_response }}"

- name: Logout
  delegate_to: localhost
  check_point_mgmt:
    command: logout
    session-data: "{{ login_response }}"
````

Note that there are outstanding issues with this, because the Ansible scripts for Check Point are not idempotent, so when you ask it to create a host, it doesn't then check whether that host exists *first*, and just tries to create it, and so on.
